[package]
name = "rssbot"
version = "2.0.0"
authors = ["iovxw <iovxw@outlook.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4"
once_cell = "1.3"
anyhow = "1.0"
structopt = "0.3"
tokio = { version = "0.2", features = ["full"] }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.3"
quick-xml = "0.18"
chrono = "0.4"

[dependencies.tbot]
version = "0.5"
default-features = false
features = ["rustls"]

[dependencies.reqwest]
version = "0.10"
default-features = false
features = ["rustls-tls", "gzip", "json", "trust-dns"]
